config/routes.rb
BackendVII::Application.routes.draw do
  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  controller :scripts do
    get 'scripts/show' => :show
    get 'scripts/download' => :download
  end
  
  resources :users
  resources :usagerecords
  resources :resolutions
  resources :homepages
  resources :events
  resources :webcalls
  resources :frontends
  resources :pages
  resources :timelines

  root :to => 'welcome#index'

end

app/models/usagerecord.rb
class Usagerecord < ActiveRecord::Base
  #belongs_to :homepage
end

app/controllers/usagerecords_controller.rb
class UsagerecordsController < ApplicationController
  skip_before_filter :authorize

  # GET /usagerecords
  # GET /usagerecords.json
  def index
    @usagerecords = Usagerecord.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @usagerecords }
    end
  end

  def get_browser_charts
    @browser_charts = Usagerecord.select("browser, count(id) as requests" ).group("browser")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @browser_charts }
    end
  end


  # GET /usagerecords/1
  # GET /usagerecords/1.json
  def show
    @usagerecord = Usagerecord.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @usagerecord }
    end
  end

  # GET /usagerecords/new
  # GET /usagerecords/new.json
  def new
    @usagerecord = Usagerecord.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @usagerecord }
    end
  end

  # GET /usagerecords/1/edit
  def edit
    @usagerecord = Usagerecord.find(params[:id])
  end

  # POST /usagerecords
  # POST /usagerecords.json
  def create
    @usagerecord = Usagerecord.new(params[:usagerecord])

    respond_to do |format|
      if @usagerecord.save
        format.html { redirect_to @usagerecord, notice: 'Usagerecord was successfully created.' }
        format.json { render json: @usagerecord, status: :created, location: @usagerecord }
      else
        format.html { render action: "new" }
        format.json { render json: @usagerecord.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /usagerecords/1
  # PUT /usagerecords/1.json
  def update
    @usagerecord = Usagerecord.find(params[:id])

    respond_to do |format|
      if @usagerecord.update_attributes(params[:usagerecord])
        format.html { redirect_to @usagerecord, notice: 'Usagerecord was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @usagerecord.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usagerecords/1
  # DELETE /usagerecords/1.json
  def destroy
    @usagerecord = Usagerecord.find(params[:id])
    @usagerecord.destroy

    respond_to do |format|
      format.html { redirect_to usagerecords_url }
      format.json { head :ok }
    end
  end
end

app/helpers/usagerecords_helper.rb
module UsagerecordsHelper
end

app/views/usagerecords/_form.html.erb
<%= form_for(@usagerecord) do |f| %>
  <% if @usagerecord.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usagerecord.errors.count, "error") %> prohibited this usagerecord from being saved:</h2>

      <ul>
      <% @usagerecord.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :browser %><br />
    <%= f.text_field :browser %>
  </div>
  <div class="field">
    <%= f.label :language %><br />
    <%= f.text_field :language %>
  </div>
  <div class="field">
    <%= f.label :timestamp %><br />
    <%= f.datetime_select :timestamp %>
  </div>
  <div class="field">
    <%= f.label :fk_idHomepage %><br />
    <%= f.number_field :fk_idHomepage %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usagerecords/edit.html.erb
<h1>Editing usagerecord</h1>

<%= render 'form' %>

<%= link_to 'Show', @usagerecord %> |
<%= link_to 'Back', usagerecords_path %>

app/views/usagerecords/get_browser_charts.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= "get_browser_charts" %>

app/views/usagerecords/index.html.erb
<h1>Listing usagerecords</h1>

<table>
  <tr>
    <th>Browser</th>
    <th>Language</th>
    <th>Timestamp</th>
    <th>URL</th>
    <th>Resolution</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @usagerecords.each do |usagerecord| %>
  <tr>
    <td><%= usagerecord.browser %></td>
    <td><%= usagerecord.language %></td>
    <td><%= usagerecord.timestamp %></td>
    <td><%= usagerecord.homepage %></td>
    <td><%= usagerecord.resolution %></td>
    <td><%= link_to 'Show', usagerecord %></td>
    <td><%= link_to 'Edit', edit_usagerecord_path(usagerecord) %></td>
    <td><%= link_to 'Destroy', usagerecord, confirm: 'Are you sure?', method: :delete %></td>

  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Usagerecord', new_usagerecord_path %>

app/views/usagerecords/new.html.erb
<h1>New usagerecord</h1>

<%= render 'form' %>

<%= link_to 'Back', usagerecords_path %>

app/views/usagerecords/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Browser:</b>
  <%= @usagerecord.browser %>
</p>

<p>
  <b>Language:</b>
  <%= @usagerecord.language %>
</p>

<p>
  <b>Timestamp:</b>
  <%= @usagerecord.timestamp %>
</p>

<p>
  <b>URL:</b>
  <%= @usagerecord.homepage %>
</p>
<p>
  <b>Resolution:</b>
  <%= @usagerecord.resolution %>
</p>


<%= link_to 'Edit', edit_usagerecord_path(@usagerecord) %> |
<%= link_to 'Back', usagerecords_path %>