config/routes.rb
BackendVII::Application.routes.draw do
  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  controller :scripts do
    get 'scripts/show' => :show
    get 'scripts/download' => :download
  end
  
  resources :users
  resources :usagerecords
  resources :resolutions
  resources :homepages
  resources :events
  resources :webcalls
  resources :frontends
  resources :pages
  resources :timelines

  root :to => 'welcome#index'

end

app/models/homepage.rb
class Homepage < ActiveRecord::Base
  #has_many :usagerecords, dependent: :destroy
end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
  skip_before_filter :authorize

  # GET /homepages
  # GET /homepages.json
  def index
    @homepages = Homepage.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @homepages }
    end
  end

  # GET /homepages/1
  # GET /homepages/1.json
  def show
    @homepage = Homepage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @homepage }
    end
  end

  # GET /homepages/new
  # GET /homepages/new.json
  def new
    @homepage = Homepage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @homepage }
    end
  end

  # GET /homepages/1/edit
  def edit
    @homepage = Homepage.find(params[:id])
  end

  # POST /homepages
  # POST /homepages.json
  def create
    @homepage = Homepage.new(params[:homepage])

    respond_to do |format|
      if @homepage.save
        format.html { redirect_to @homepage, notice: 'Homepage was successfully created.' }
        format.json { render json: @homepage, status: :created, location: @homepage }
      else
        format.html { render action: "new" }
        format.json { render json: @homepage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /homepages/1
  # PUT /homepages/1.json
  def update
    @homepage = Homepage.find(params[:id])

    respond_to do |format|
      if @homepage.update_attributes(params[:homepage])
        format.html { redirect_to @homepage, notice: 'Homepage was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @homepage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homepages/1
  # DELETE /homepages/1.json
  def destroy
    @homepage = Homepage.find(params[:id])
    @homepage.destroy

    respond_to do |format|
      format.html { redirect_to homepages_url }
      format.json { head :ok }
    end
  end
end

app/helpers/homepages_helper.rb
module HomepagesHelper
end

app/views/homepages/_form.html.erb
<%= form_for(@homepage) do |f| %>
  <% if @homepage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@homepage.errors.count, "error") %> prohibited this homepage from being saved:</h2>

      <ul>
      <% @homepage.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :beschreibung %><br />
    <%= f.text_field :beschreibung %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homepages/edit.html.erb
<h1>Editing homepage</h1>

<%= render 'form' %>

<%= link_to 'Show', @homepage %> |
<%= link_to 'Back', homepages_path %>

app/views/homepages/index.html.erb
<h1>Listing homepages</h1>

<table>
  <tr>
    <th>Url</th>
    <th>Name</th>
    <th>Beschreibung</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @homepages.each do |homepage| %>
  <tr>
    <td><%= homepage.url %></td>
    <td><%= homepage.name %></td>
    <td><%= homepage.beschreibung %></td>
    <td><%= link_to 'Show', homepage %></td>
    <td><%= link_to 'Edit', edit_homepage_path(homepage) %></td>
    <td><%= link_to 'Destroy', homepage, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Homepage', new_homepage_path %>

app/views/homepages/new.html.erb
<h1>New homepage</h1>

<%= render 'form' %>

<%= link_to 'Back', homepages_path %>

app/views/homepages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Url:</b>
  <%= @homepage.url %>
</p>

<p>
  <b>Name:</b>
  <%= @homepage.name %>
</p>

<p>
  <b>Beschreibung:</b>
  <%= @homepage.beschreibung %>
</p>


<%= link_to 'Edit', edit_homepage_path(@homepage) %> |
<%= link_to 'Back', homepages_path %>